<script type="text/javascript">
    //<![CDATA[
    function initCampaignMonitor($) {
        var field = $('#campaignmonitor_configuration');
        var fieldClientId = $('#campaignmonitor_configuration_client_id');
        var rowApiKey = $('#row_campaignmonitor_configuration_subscribe_list_api_key');
        var select = $(rowApiKey).find('.select');

        field.prepend('<img src="//www.weprovide.com/assets/themes/weprovide/dist/images/logo/weprovide-logo-small.svg" style="height: 100px; padding: 10px;" />');
        rowApiKey.hide();

        $('#campaignmonitor_configuration_client_id').change(function() {
            var clientId = $(this).val();
            if(clientId.length == 0){
                rowApiKey.hide();
            }else {
                fieldClientId.parent().append('<img src="<?php echo $this->getSkinUrl('images/campaignmonitor/loader.gif'); ?>" id="campaignmonitor_loader" style="float: right; padding-left: 0;">');
                $.get('<?php echo Mage::helper("adminhtml")->getUrl('adminhtml/cm/ajaxSubscribeList'); ?>', {client_id: clientId})
                    .done(function (data) {
                        rowApiKey.show();

                        var items = "";
                        $.each(data, function (key, val) {
                            items += '<option value="' + val.ListID + '">' + val.Name + '</option>';
                        });
                        $(select).html(items);
                        $('#campaignmonitor_loader').remove();
                    });
            }
        });
    }
    //]]>
</script>

